### ISSUE TITLE
multiple connections and/or persist connection init info?

### ISSUE THREAD

**Issue by ghost** [pirate/WebRTCChat#3]
I tested this out, looks pretty useful. I wonder how hard the 2 things I mentioned in the title would be to achieve[they may be impossible, input please]?

to clarify: 
1) what would be some paths of least resistance to having more than 2 people connected together? Would it even be possible for more than one person to use the same session-init-credentials? or would that cause interference?  

2) after a successful 'handshake'/session-init, is there any chance some credentials could be persisted - so that the next time the html was fired up, a connection can happen more automatically?

**Comment by pirate** [comment]
1. Unfortunately I think big groups are infeasible as everyone has to send/receive every video stream individually to every other member, and connections+bandwidth will go up linearly with O(n). instead of being O(1) with a central server that mirrors all the video back out over one-connection-per-peer.
2. Not that I know of, because you have to re-advertise the ip and port combos that are available on each connection, if either client moved to a new network the old connection handshake would be useless.
